<html>
<head>
    <meta>
    <style>
        body {
            font: normal 100% Helvetica, Arial, sans-serif;
        }
    </style>
</head>
<body>
    <div style="display: block; position: fixed;width: 90%;height: 8%;background-color:white; margin-left:5%;margin-top:5px;padding:2px;border:lightgrey solid 3px;">
        <input type="text" style="height:100%;width:70%;">
        <button type="button" style="height:100%;width:25%;background-color:lightgreen;margin-left: 3%;">搜索</button>
    </div>
    <div style="width:100%;">
        <?php foreach($data as $k => $v) { ?>
            <div style="width:100%;">
                <img style="width:100%;" src="<?php print_r($v->{'film_img'}); ?>" />
            </div>
            <div>
                <span style="font-size:3.2em;"><?php echo print_r($v->{'film_sort_desc'}); ?></span>
            </div>

        <?php } ?>


    </div>
</body>
</html>